[project]
name = "saga"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "commitizen>=4.9.1",
    "fastapi>=0.120.2",
    "pymilvus>=2.6.2",
    "uvicorn>=0.38.0",
]
